import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })


export default function create (){
    return (
        <>
        <Head>
            <title>Gear Hackathon 2022</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        

        <main className={styles.main}>
            <Image className={styles.logo}
                src="/logo_diary.png"
                alt=""
                width={100}
                height={100}
            />
            <div className={styles.card}>
                <a
                    href="/principal"
                    className={styles.card}
                    target="_blank"
                    rel="noopener noreferrer"
                >
                <h1 className={inter.className}>
                    Decentralized Diary
                </h1>
                </a>
            </div>
            <div className={styles.card}>
                <Image className={styles.logo}
                    src="/cafe.webp"
                    alt=""
                    width={350}
                    height={350}
                />
            </div>
            <div className={styles.card}>
                <h2 className={inter.className}>
                    Coffee date with bae
                </h2>
                <p className={inter.className}>
                    Had a great time today! ilysm @sam161222 After this we went window shopping and I found the most amazing dress for my graduation party. So excited!!!
                </p>
            </div>
                <div className={styles.card}>
                <a></a>
                <a
                    href="/principal"
                    className={styles.card}
                    target="_blank"
                    rel="noopener noreferrer"
                >
                <h2 className={inter.className}>
                    Home <span>-&gt;</span>
                </h2>
                </a>                
          </div>
            </main></>
    )
}