import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })


export default function create (){
    return (
        <>
        <Head>
            <title>Gear Hackathon 2022</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        

        <main className={styles.main}>
            <Image className={styles.logo}
                src="/logo_diary.png"
                alt=""
                width={100}
                height={100}
            />
            <div className={styles.card}>
                <h1 className={inter.className}>
                    Join the Decentralized Diary
                </h1>
            </div>
            <div className={styles.card}>
                <h2 className={inter.className}>
                    Create an account with your Polkadot Wallet
                </h2>
                <input type="text" id="account" name="Acount" maxlength="50"></input>
            </div>
            
                <div className={styles.card}>
                <a></a>
                <a
                    href="/principal"
                    className={styles.card}
                    target="_blank"
                    rel="noopener noreferrer"
                >
                <h2 className={inter.className}>
                    Let's go! <span>-&gt;</span>
                </h2>
                </a>                
          </div>
            </main></>
    )
}