import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })


export default function create (){
    return (
        <>
        <Head>
            <title>Gear Hackathon 2022</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        

        <main className={styles.main}>
            <Image className={styles.logo}
                src="/logo_diary.png"
                alt=""
                width={100}
                height={100}
            />
            <div className={styles.card}>
            <h1 className={inter.className}>
                Decentralized Diary
            </h1>
            <p className={inter.className}>
                Welcome Home, Danya
            </p>
            </div>
            <div className={styles.card}>
                <a
                    href="/create"
                    className={styles.card}
                    target="_blank"
                    rel="noopener noreferrer"
                >
                <h2 className={inter.className}>
                    Create new entry <span>-&gt;</span>
                </h2>
            </a>                
        </div>

        <div className={styles.grid}>
            <a
                href="/demo1"
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
            >
                <div className={styles.center}>
                    <Image className={styles.logo}
                        src="/examen.webp"
                        alt=""
                        width={350}
                        height={350}
                    />
                </div>
                <h2 className={inter.className}>
                    Today was my last final <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    #officiallyunemployed
                </p>
            </a>
            <a
                href="/demo1"
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
            >
                <div className={styles.center}>
                    <Image className={styles.logo}
                        src="/picnic.webp"
                        alt=""
                        width={350}
                        height={350}
                    />
                </div>
                <h2 className={inter.className}>
                    Drinks w friends @ Dito's<span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    The best negroni sbagliato...
                </p>
            </a>
            <a
                href="/demo1"
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
            >
                <div className={styles.center}>
                    <Image className={styles.logo}
                        src="/fiesta.png"
                        alt=""
                        width={350}
                        height={350}
                    />
                </div>
                <h2 className={inter.className}>
                    Graduation Party! <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    FINALLY! I waited so long for...
                </p>
            </a>
            <a
                href="/demo1"
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
            >
                <div className={styles.center}>
                    <Image className={styles.logo}
                        src="/hackathon.webp"
                        alt=""
                        width={350}
                        height={350}
                    />
                </div>
                <h2 className={inter.className}>
                    Gear Hackathon! So fun <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    We're learning about Web3 and block...
                </p>
            </a>
            <a
                href="/demo1"
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
            >
                <div className={styles.center}>
                    <Image className={styles.logo}
                        src="/cafe.webp"
                        alt=""
                        width={350}
                        height={350}
                    />
                </div>
                <h2 className={inter.className}>
                    Coffee date with bae <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    Had a great time today! ilysm
                </p>
            </a>
        </div>
        <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
        </a>

        <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
        </a>

        <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
        </a>
        <div className={styles.card}>
            <h1 className={inter.className}>
              Memories captured forever. Thoughts made into art.
            </h1>
        </div>
        <div className={styles.card}>
          <h3 className={inter.className}>
            Decentralized Diary, created in the 1er Hackathon Web3 Universitario en México 2022.
          </h3>
        </div>
            </main></>
    )
}